### ISSUE TITLE
Radio still works when removed if on.

### ISSUE THREAD

**Issue by norwayRP** [DNDdjay/RP_radio#1]
When a player has the radio on and hidden, it continous to work after its been removed. Got any workaround for that?

**Comment by DNDdjay** [comment]
sorry after mumble is outdated i dont support the script any more

**Comment by DNDdjay** [comment]
i have updatede the rp-radio for pma voice here https://github.com/DNDdjay/rp-radio-pma-voice/tree/V1.1

there is the functions you are asking about
